### ISSUE TITLE
Drive link not working

### ISSUE THREAD

**Issue by babhero10** [MeshFormer/MeshFormer#2]
It is unclear how to prepare my dataset to work with the code and I tried to download the pretrained model and dataset and the link is 404 not found

**Comment by lidan233** [comment]
Because my google account is suspended, these data files might be removed. I am trying to get them back in this week and release more code.

**Comment by MeshFormer** [comment]
I have already added the links to the datasets and pretrained models. You can check them now. If you have any further questions, let me know.

**Comment by babhero10** [comment]
Thank you very much for the help! but now there is a permission problem with the google drive link (Access denied)

**Comment by MeshFormer** [comment]
Sorry for the late response.  I update the permission.

**Comment by babhero10** [comment]
No problem! Thank you so much the link is working now.
